// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73yWPJv0ThkoZoyoEypuZeA6GIoyrPY8',
    appId: '1:736380691407:web:6c2e76fe6372ab9d8ba8ba',
    messagingSenderId: '736380691407',
    projectId: 'handover-378414',
    authDomain: 'handover-378414.firebaseapp.com',
    storageBucket: 'handover-378414.appspot.com',
    measurementId: 'G-D4EC9JL8T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHTaiirj1ugF3wOV9kgBYlQsC2-by_ik',
    appId: '1:736380691407:android:54bc9ecffeba628a8ba8ba',
    messagingSenderId: '736380691407',
    projectId: 'handover-378414',
    storageBucket: 'handover-378414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_HG5_ckY4V0xXPFglRzLTAGkbOn77nU',
    appId: '1:736380691407:ios:1b3c0770f5a7a09d8ba8ba',
    messagingSenderId: '736380691407',
    projectId: 'handover-378414',
    storageBucket: 'handover-378414.appspot.com',
    iosClientId: '736380691407-38rra2gm4bn0sctrkq6hq25h94hvjrc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.handover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP_HG5_ckY4V0xXPFglRzLTAGkbOn77nU',
    appId: '1:736380691407:ios:1b3c0770f5a7a09d8ba8ba',
    messagingSenderId: '736380691407',
    projectId: 'handover-378414',
    storageBucket: 'handover-378414.appspot.com',
    iosClientId: '736380691407-38rra2gm4bn0sctrkq6hq25h94hvjrc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.handover',
  );
}
